version: '3,8'

services:
  ###############################
  #           bot trading       #
  ###############################
    go:
        depends_on:
            - mysql
        image: go
        restart: always
        build:
            context: ./requirements/go/
            dockerfile: Dockerfile 
        environment:
            # - ID_CHANNEL=${ID_CHANNEL} 
            - API=${API}
            - API_SECRET=${API_SECRET}
            - API_TELEGRAM=${API_TELEGRAM}
            - URL=${URL}
            - ADMIN=${ADMIN}
        ports:
          - "30000:30000"
        networks:
             bot:

  ###############################
  #           python bot        #
  ###############################
    python:
        image: python
        restart: always
        build:
            context: ./requirements/python/
            dockerfile: Dockerfile 
        environment:
          # - ID_CHANNEL=${ID_CHANNEL} 
          - API_ID=${API_ID}
          - API_HASH=${API_HASH}
          - SIGNAL_CHANNEL=${SIGNAL_CHANNEL} 
          - BOT_NAME=${BOT_NAME} 
        ports:
          - "40000:40000"
        networks:
             bot:

  ###############################
  #           mariadb           #
  ###############################
    mysql:
        image: mariadb:latest
        restart: always
        container_name: db
        environment:
          - MYSQL_DATABASE=db
          - MARIADB_USER=bot 
          - MARIADB_PASSWORD=bot
          - MARIADB_ROOT_PASSWORD=bot
        ports:
          - "3306:3306"
        expose:
          - "3306"
        env_file: .env
        volumes:
          - ${PWD}/mariadb:/var/lib/mysql
        networks:
             bot:

networks:
     bot:
        driver: bridge
